name: 'WGExtender'
main: wgextender.WGExtender
api-version: '1.20'
version: '${project.version}-x'
authors: [_Shevchik_, imDaniX]
depend: [WorldGuard, WorldEdit]
softdepend: [PlaceholderAPI]
folia-supported: true
commands:
  wgextender:
    aliases: [wgex]
